### ISSUE TITLE
Error when creating a collection on color attribute

### ISSUE THREAD

**Issue by rodo** [flovouin/terraform-provider-metabase#35]
Hi,
With 
* metabase v0.48.3
* provider version 0.3.0

I have an error when I create a new collection, the collection is well created but I have the following on console when doing the `terraform apply`

```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to metabase_collection.my_business_reports, provider
│ "provider[\"registry.terraform.io/flovouin/metabase\"]" produced an unexpected new value: .color: was
│ cty.StringVal("#cdeabc"), but now null.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

Thank you for your work :+1:

**Comment by flovouin** [comment]
Hi @rodo,

Thanks for your report. The Metabase API has changed quite a bit in the last few versions, and there has been several breaking changes (see #31). This provider does not currently support Metabase v0.48.

However I'm in the process of supporting it! A [branch](https://github.com/flovouin/terraform-provider-metabase/tree/chore/metabase-0-48) already exists, but is not quite finished. In fact, the color issue has been fixed in [this commit](https://github.com/flovouin/terraform-provider-metabase/commit/7ae99f95eafa93a54a4bd57f96db54b57a001c11).

Work has been slower than I originally hoped due to personal matters, but I haven't given up on finishing this.
