### ISSUE TITLE
Support API Keys

### ISSUE THREAD

**Issue by michal-billtech** [flovouin/terraform-provider-metabase#44]
Metabase added support for [API Keys](https://www.metabase.com/docs/master/people-and-groups/api-keys) in v0.49. It would be wonderful if we could supply an api key instead of username+password in the provider setup.

**Comment by flovouin** [comment]
Hey @michal-billtech,
Thanks for the suggestion. I wasn't aware of this feature and that's good news.
I've just released `v0.5.0` of the provider, which optionally accepts an `api_key` instead of a username and password pair.
I haven't tested it on a "real" Metabase instance, however there's a passing acceptance test for it.
Tell me if it does the trick for you.
Cheers.
